### PR TITLE
Added schema endpoint responding to OPTIONS

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by fiunchinho** [comment]
Couldn't we use io.netty.handler.codec.http.HttpHeaders for header names?

**Comment by enriclluelles** [comment]
:+1: when the tests pass :trollface:

**Comment by albertoramirezscmspain** [comment]
Fixed issues and start using ```io.netty.handler.codec.http.HttpHeaders```.

**Comment by fiunchinho** [comment]
:+1:

**Comment by ghost** [comment]
Fixes #5

**Pull request merged**
